{"name": "testcaseyhgllistdata", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n3 Failed Assumptions:\n\ntestcase_001.py:76: AssumptionFailure\n>>\tpytest.assume(str(uilistdata[x][0]) == str(sqllistdata[x][0]))\nAssertionError: assert False\n\ntestcase_001.py:79: AssumptionFailure\n>>\tpytest.assume(str(uilistdata[x][1]) == str(sqllistdata[x][1]))\nAssertionError: assert False\n\ntestcase_001.py:82: AssumptionFailure\n>>\tpytest.assume(str(uilistdata[x][2]) == str(sqllistdata[x][2]))\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               3 Failed Assumptions:\nE               \nE               testcase_001.py:76: AssumptionFailure\nE               >>\tpytest.assume(str(uilistdata[x][0]) == str(sqllistdata[x][0]))\nE               AssertionError: assert False\nE               \nE               testcase_001.py:79: AssumptionFailure\nE               >>\tpytest.assume(str(uilistdata[x][1]) == str(sqllistdata[x][1]))\nE               AssertionError: assert False\nE               \nE               testcase_001.py:82: AssumptionFailure\nE               >>\tpytest.assume(str(uilistdata[x][2]) == str(sqllistdata[x][2]))\nE               AssertionError: assert False\n\n../../../Library/Python/3.7/lib/python/site-packages/six.py:692: FailedAssumption"}, "steps": [{"name": "校验用户管理列表数据中的用户ID", "status": "passed", "start": 1603422673132, "stop": 1603422673211}, {"name": "校验用户管理列表数据中的用户手机号", "status": "passed", "start": 1603422673211, "stop": 1603422673214}, {"name": "校验用户管理列表数据中的用户昵称", "status": "passed", "start": 1603422673214, "stop": 1603422673216}, {"name": "校验用户管理列表数据中的用户ID", "status": "passed", "start": 1603422673216, "stop": 1603422673218}, {"name": "校验用户管理列表数据中的用户手机号", "status": "passed", "start": 1603422673218, "stop": 1603422673220}, {"name": "校验用户管理列表数据中的用户昵称", "status": "passed", "start": 1603422673220, "stop": 1603422673222}], "attachments": [{"name": "log", "source": "5b397236-b470-4676-b220-e630df18ce65-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "0fed8af9-ad97-4ca7-9250-1d8eace0a184-attachment.txt", "type": "text/plain"}], "start": 1603422671028, "stop": 1603422673222, "uuid": "21154a39-c849-4092-896b-34746f6a427f", "historyId": "a0fb5fc6d8aa456afbffd08af60d7023", "testCaseId": "76b95cfc4fbd8a3dfeceba5453d33f5e", "fullName": "testcase_001.Testcase#testcaseyhgllistdata", "labels": [{"name": "story", "value": "列表数据测试"}, {"name": "suite", "value": "testcase_001"}, {"name": "subSuite", "value": "Testcase"}, {"name": "host", "value": "huangwenjiaodeMacBook-Pro.local"}, {"name": "thread", "value": "1270-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase_001"}]}